language: python
python:
  - 2.7
env:
  - LOGGER_SETTINGS_FILE=./config.ini
before_install:
    - pip install --upgrade 'setuptools<45' pip
    - pip install -r requirements.txt
install: 
  - python setup.py install
script:
  - python setup.py test
before_script:
  - cp ./config.ini.template ./config.ini
  - cp logger/robots.txt ./robots.txt
